[theme]
base="light"

[server]
headless = true

[client]
toolbarMode = "minimal"
showSidebarNavigation = true

[global]
developmentMode = false

[runner]
magicEnabled = true

[browser]
gatherUsageStats = false

[ui]
pageTitle = "ğŸ» Beer Diary"
pageIcon = "ğŸº"
layout = "wide"
