[theme]
base="dark"

[server]
headless = true

[client]
toolbarMode = "minimal"
showSidebarNavigation = true

[global]
developmentMode = false

[runner]
magicEnabled = true

[ui]
pageTitle = "ğŸ» Beer Diary"
pageIcon = "ğŸº"
layout = "wide"  # â¬…ï¸ Key part
