[[pages]]
path = "app.py"
name = "ğŸ  Home"
icon = "house"

[[pages]]
path = "pages/2_ğŸ»_Explore_Beers.py"
name = "ğŸ» Explore Beers"
icon = "beers"

[[pages]]
path = "pages/3_ğŸ“”_My_Tasting_Journal.py"
name = "ğŸ“” My Tasting Journal"
icon = "book"

[[pages]]
path = "pages/4_ğŸ“Š_Style_Explorer.py"
name = "ğŸ“Š Style Explorer"
icon = "chart-bar"

[[pages]]
path = "pages/5_ğŸ—ºï¸_Brewery_Locator.py"
name = "ğŸ—ºï¸ Brewery Locator"
icon = "map"

[[pages]]
path = "pages/6_ğŸ“œ_My_Favorite_Breweries.py"
name = "ğŸ—ºï¸ My Favorite Breweries.py"
icon = "scroll"
